// Deadlimit Shade — Deadlock hero material bootstrap for Substance 3D Painter.
//
// The common metal/rough baseline is extended with the statically recovered Deadlock
// NPR direct-diffuse equation. Runtime globals that have not been captured remain
// explicit calibration controls and are not presented as retail defaults.

import lib-sss.glsl
import lib-pbr.glsl
import lib-emissive.glsl
import lib-pom.glsl
import lib-utils.glsl

// Retail preview textures use ordinary sampler2D resources and must remain
// valid for the whole mesh while Painter is painting another Texture Set.
// Painter otherwise applies its local sampling optimization and can display
// saturated cyan/blue tiles outside the currently active set.
//: state nonlocal on

// BEGIN GENERATED CHARACTER PROFILES
// Generated by tools/Generate-CharacterProfiles.ps1. Do not edit by hand.
// Source of truth: profiles/*.json.

const int DL_CHARACTER_CUSTOM = 0;
const int DL_CHARACTER_IVY = 1;

struct DLCharacterProfile
{
  bool directDiffuseEnabled;
  float directDiffuseStepSharpness;
  float directDiffusePbrBlend;
  float directDiffuseWrap;
  float directDiffuseNormalization;
  vec3 referenceTint;
  bool outlineEnabled;
  vec3 outlineColor;
};

DLCharacterProfile dlCharacterProfileIvy()
{
  DLCharacterProfile profile;
  profile.directDiffuseEnabled = true;
  profile.directDiffuseStepSharpness = 0.75;
  profile.directDiffusePbrBlend = 0.25;
  profile.directDiffuseWrap = 0.5;
  profile.directDiffuseNormalization = 1.0;
  profile.referenceTint = vec3(0.321569, 0.388235, 0.176471);
  profile.outlineEnabled = true;
  profile.outlineColor = vec3(0.164706, 0.054902, 0.054902);
  return profile;
}

DLCharacterProfile dlBuiltInCharacterProfile(int characterId)
{
  if (characterId == DL_CHARACTER_IVY)
  {
    return dlCharacterProfileIvy();
  }

  // Callers handle Custom separately. This is a deterministic fallback.
  return dlCharacterProfileIvy();
}
// END GENERATED CHARACTER PROFILES

//: param auto channel_basecolor
uniform SamplerSparse basecolor_tex;

//: param auto channel_roughness
uniform SamplerSparse roughness_tex;

//: param auto channel_metallic
uniform SamplerSparse metallic_tex;

//: param auto channel_specularlevel
uniform SamplerSparse specularlevel_tex;

// Optional default-character preview maps. They are decoded locally from the
// artist's Deadlimit 0source extraction or its recorded read-only retail VPK.
// They bypass Painter channels only on the dedicated Valve Texture Sets.
//: param custom {
//:   "default": false,
//:   "label": "Use Default Retail Inputs",
//:   "group": "Deadlimit Retail Preview"
//: }
uniform bool dl_use_retail_inputs;

//: param custom { "default": "", "default_color": [1.0, 1.0, 1.0, 1.0], "label": "Color + Metalness", "usage": "texture", "group": "Deadlimit Retail Preview" }
uniform sampler2D dl_retail_color;

// ValveResourceFormat presents the packed retail normal as decoded tangent
// normal RGB and the processed roughness as A.
//: param custom { "default": "", "default_color": [0.5, 0.5, 1.0, 0.5], "label": "Normal + Roughness", "usage": "texture", "group": "Deadlimit Retail Preview" }
uniform sampler2D dl_retail_normal_roughness;

//: param custom { "default": "", "default_color": [1.0, 1.0, 1.0, 1.0], "label": "Ambient Occlusion", "usage": "texture", "group": "Deadlimit Retail Preview" }
uniform sampler2D dl_retail_ambient_occlusion;

//: param custom {
//:   "default": 0,
//:   "label": "Character",
//:   "widget": "combobox",
//:   "values": {
// BEGIN GENERATED CHARACTER SELECTOR
//:     "Custom": 0,
//:     "Ivy": 1
// END GENERATED CHARACTER SELECTOR
//:   },
//:   "group": "Deadlimit Character"
//: }
uniform int dl_character;

//: param custom {
//:   "default": false,
//:   "label": "Use Custom Calibration",
//:   "group": "Deadlimit Character",
//:   "description": "Use the calibration controls below instead of the selected character profile values."
//: }
uniform bool dl_use_custom_calibration;

//: param custom {
//:   "default": false,
//:   "label": "NPR Direct Diffuse",
//:   "group": "Deadlimit NPR Calibration"
//: }
uniform bool dl_npr_direct_diffuse;

//: param custom {
//:   "default": 0.75,
//:   "label": "Diffuse Step Sharpness",
//:   "min": 0.0,
//:   "max": 0.95,
//:   "group": "Deadlimit NPR Calibration"
//: }
uniform float dl_npr_diffuse_step_sharpness;

//: param custom {
//:   "default": 0.25,
//:   "label": "Diffuse PBR Blend",
//:   "min": 0.0,
//:   "max": 1.0,
//:   "group": "Deadlimit NPR Calibration"
//: }
uniform float dl_npr_diffuse_pbr_blend;

//: param custom {
//:   "default": 0.5,
//:   "label": "Direct Light Wrap",
//:   "min": 0.0,
//:   "max": 1.0,
//:   "group": "Deadlimit NPR Calibration"
//: }
uniform float dl_npr_direct_light_wrap;

//: param custom {
//:   "default": 1.0,
//:   "label": "Direct Light Normalization",
//:   "min": 0.0,
//:   "max": 4.0,
//:   "group": "Deadlimit NPR Calibration"
//: }
uniform float dl_npr_direct_light_normalization;

//: param custom {
//:   "default": [0.35, 0.6, 0.72],
//:   "label": "Key Light Direction",
//:   "min": -1.0,
//:   "max": 1.0,
//:   "group": "Deadlimit Preview Lighting",
//:   "description": "World-space direction from the surface toward the preview key light."
//: }
uniform vec3 dl_key_light_direction;

//: param custom {
//:   "default": [1.0, 0.95, 0.9],
//:   "label": "Key Light Color",
//:   "widget": "color",
//:   "group": "Deadlimit Preview Lighting"
//: }
uniform vec3 dl_key_light_color;

//: param custom {
//:   "default": 0.75,
//:   "label": "Key Light Intensity",
//:   "min": 0.0,
//:   "max": 4.0,
//:   "group": "Deadlimit Preview Lighting"
//: }
uniform float dl_key_light_intensity;

//: param custom {
//:   "default": 0.65,
//:   "label": "Environment Diffuse",
//:   "min": 0.0,
//:   "max": 2.0,
//:   "group": "Deadlimit Preview Lighting"
//: }
uniform float dl_environment_diffuse;

//: param custom {
//:   "default": 0.0,
//:   "label": "Vertex Color Multiply",
//:   "min": 0.0,
//:   "max": 1.0,
//:   "group": "Deadlimit Retail Preview",
//:   "description": "VMAT-driven color0 multiplication. Apply Deadlimit configures this from F_VERTEX_COLOR and g_fVertexColorStrength1."
//: }
uniform float dl_vertex_color_multiply;

//: param custom {
//:   "default": 0,
//:   "label": "Debug View",
//:   "widget": "combobox",
//:   "values": {
//:     "Shaded": 0,
//:     "Base Color": 1,
//:     "Roughness": 2,
//:     "Metallic": 3,
//:     "Ambient Occlusion": 4,
//:     "Vertex Color RGB": 5,
//:     "Vertex Color Alpha": 6,
//:     "N dot L (Signed)": 7,
//:     "Wrapped Direct Diffuse": 8,
//:     "Quantized Direct Diffuse": 9,
//:     "Final Direct Diffuse": 10,
//:     "Character Profile": 11
//:   },
//:   "group": "Deadlimit Diagnostics"
//: }
uniform int dl_debug_view;

struct DLDirectDiffuseSample
{
  float ndotl;
  float lambert;
  float wrapped;
  float quantized;
  float finalValue;
};

DLCharacterProfile dlCustomCharacterProfile()
{
  DLCharacterProfile profile;
  profile.directDiffuseEnabled = dl_npr_direct_diffuse;
  profile.directDiffuseStepSharpness = dl_npr_diffuse_step_sharpness;
  profile.directDiffusePbrBlend = dl_npr_diffuse_pbr_blend;
  profile.directDiffuseWrap = dl_npr_direct_light_wrap;
  profile.directDiffuseNormalization = dl_npr_direct_light_normalization;
  profile.referenceTint = vec3(0.18);
  profile.outlineEnabled = true;
  profile.outlineColor = vec3(0.08, 0.02, 0.02);
  return profile;
}

DLCharacterProfile dlActiveCharacterProfile()
{
  if (dl_character == DL_CHARACTER_CUSTOM || dl_use_custom_calibration)
  {
    return dlCustomCharacterProfile();
  }

  return dlBuiltInCharacterProfile(dl_character);
}

float dlNprQuantize(float value, float sharpness)
{
  float safeSharpness = clamp(sharpness, 0.0, 0.95);
  float base = floor(value);
  float fraction = fract(value);
  float wing = fraction > 0.5 ? 1.0 - fraction : fraction;
  float exponent = 1.0 / (1.0 - safeSharpness);

  // Algebraically equivalent to pow(0.5, 1.0 - exponent) * pow(wing, exponent),
  // with stable behavior as sharpness approaches its supported upper bound.
  float shapedWing = 0.5 * pow(2.0 * wing, exponent);
  return base + (fraction > 0.5 ? 1.0 - shapedWing : shapedWing);
}

DLDirectDiffuseSample dlEvaluateDirectDiffuse(vec3 normal, DLCharacterProfile profile)
{
  DLDirectDiffuseSample sample;
  float lightLengthSquared = dot(dl_key_light_direction, dl_key_light_direction);
  vec3 lightDirection = lightLengthSquared > 0.000001
    ? normalize(dl_key_light_direction)
    : vec3(0.0, 1.0, 0.0);

  sample.ndotl = dot(normal, lightDirection);
  sample.lambert = max(sample.ndotl, 0.0);
  sample.wrapped = clamp(
    0.5 + 2.0 * ((profile.directDiffuseWrap - 0.5) + sample.ndotl - 0.5),
    0.0,
    1.0);
  sample.quantized = dlNprQuantize(
    sample.wrapped,
    profile.directDiffuseStepSharpness);

  float nprResponse = profile.directDiffuseNormalization * sample.quantized;
  sample.finalValue = profile.directDiffuseEnabled
    ? mix(nprResponse, sample.lambert, clamp(profile.directDiffusePbrBlend, 0.0, 1.0))
    : sample.lambert;
  return sample;
}

void dlDebugOutput(vec3 value)
{
  albedoOutput(vec3(0.0));
  diffuseShadingOutput(vec3(0.0));
  specularShadingOutput(vec3(0.0));
  emissiveColorOutput(value);
  sssCoefficientsOutput(vec4(0.0));
}

void shade(V2F inputs)
{
  // Keep the bootstrap path aligned with Painter's current official metal/rough
  // reference shader before adding any Deadlock-specific transformation.
  vec3 viewTS = worldSpaceToTangentSpace(getEyeVec(inputs.position), inputs);
  applyParallaxOffset(inputs, viewTS);

  float roughness = getRoughness(roughness_tex, inputs.sparse_coord);
  vec3 baseColor = getBaseColor(basecolor_tex, inputs.sparse_coord);
  float metallic = getMetallic(metallic_tex, inputs.sparse_coord);
  float specularLevel = getSpecularLevel(specularlevel_tex, inputs.sparse_coord);
  float ambientOcclusion = getAO(inputs.sparse_coord);
  vec3 retailNormal = vec3(0.0, 0.0, 1.0);
  if (dl_use_retail_inputs)
  {
    vec4 retailColorMetalness = texture(dl_retail_color, inputs.tex_coord);
    vec4 retailNormalRoughness = texture(dl_retail_normal_roughness, inputs.tex_coord);
    baseColor = retailColorMetalness.rgb;
    metallic = retailColorMetalness.a;
    retailNormal = normalUnpack(retailNormalRoughness);
    roughness = retailNormalRoughness.a;
    ambientOcclusion = texture(dl_retail_ambient_occlusion, inputs.tex_coord).r;
  }

  vec3 vertexColor = clamp(inputs.color[0].rgb, vec3(0.0), vec3(1.0));
  float vertexAlpha = clamp(inputs.color[0].a, 0.0, 1.0);
  DLCharacterProfile characterProfile = dlActiveCharacterProfile();
  LocalVectors vectors = dl_use_retail_inputs
    ? computeLocalFrame(inputs, tangentSpaceToWorldSpace(retailNormal, inputs), 0.0)
    : computeLocalFrame(inputs);
  DLDirectDiffuseSample directDiffuse = dlEvaluateDirectDiffuse(
    vectors.normal,
    characterProfile);

  // VMAT vertex color is part of the resolved material Base Color. Apply it
  // before diagnostics so Deadlimit View -> Base Color and shaded rendering
  // show the same eyes and other vertex-colored slots.
  baseColor *= mix(vec3(1.0), vertexColor, dl_vertex_color_multiply);

  if (dl_debug_view == 1)
  {
    dlDebugOutput(baseColor);
    return;
  }
  if (dl_debug_view == 2)
  {
    dlDebugOutput(vec3(roughness));
    return;
  }
  if (dl_debug_view == 3)
  {
    dlDebugOutput(vec3(metallic));
    return;
  }
  if (dl_debug_view == 4)
  {
    dlDebugOutput(vec3(ambientOcclusion));
    return;
  }
  if (dl_debug_view == 5)
  {
    dlDebugOutput(vertexColor);
    return;
  }
  if (dl_debug_view == 6)
  {
    dlDebugOutput(vec3(vertexAlpha));
    return;
  }
  if (dl_debug_view == 7)
  {
    dlDebugOutput(vec3(0.5 + 0.5 * directDiffuse.ndotl));
    return;
  }
  if (dl_debug_view == 8)
  {
    dlDebugOutput(vec3(directDiffuse.wrapped));
    return;
  }
  if (dl_debug_view == 9)
  {
    dlDebugOutput(vec3(directDiffuse.quantized));
    return;
  }
  if (dl_debug_view == 10)
  {
    dlDebugOutput(vec3(directDiffuse.finalValue));
    return;
  }
  if (dl_debug_view == 11)
  {
    dlDebugOutput(characterProfile.referenceTint);
    return;
  }

  vec3 diffColor = generateDiffuseColor(baseColor, metallic);
  vec3 specColor = generateSpecularColor(specularLevel, baseColor, metallic);

  float occlusion = ambientOcclusion * getShadowFactor();
  float specOcclusion = specularOcclusionCorrection(occlusion, metallic, roughness);

  vec3 diffuseLighting =
    dl_environment_diffuse * envIrradiance(vectors.normal) +
    dl_key_light_intensity * dl_key_light_color * directDiffuse.finalValue;

  emissiveColorOutput(pbrComputeEmissive(emissive_tex, inputs.sparse_coord));
  albedoOutput(diffColor);
  diffuseShadingOutput(occlusion * diffuseLighting);
  specularShadingOutput(specOcclusion * pbrComputeSpecular(vectors, specColor, roughness));
  sssCoefficientsOutput(getSSSCoefficients(inputs.sparse_coord));
}
