// Deadlimit Shade — preview-only inverted-hull shell shader for Substance 3D Painter.
//
// The preview mesh generator owns shell geometry and Outline Width.
// Expected prototype contract:
//   - duplicate preview shell
//   - offset shell vertices outward
//   - reverse shell triangle winding
//   - assign preview-only material: __deadlimit_outline
//
// This shader only shades the already-generated shell.

// BEGIN GENERATED CHARACTER PROFILES
// Generated by tools/Generate-CharacterProfiles.ps1. Do not edit by hand.
// Source of truth: profiles/*.json.

const int DL_CHARACTER_CUSTOM = 0;
const int DL_CHARACTER_IVY = 1;

struct DLCharacterProfile
{
  bool directDiffuseEnabled;
  float directDiffuseStepSharpness;
  float directDiffusePbrBlend;
  float directDiffuseWrap;
  float directDiffuseNormalization;
  vec3 referenceTint;
  bool outlineEnabled;
  vec3 outlineColor;
};

DLCharacterProfile dlCharacterProfileIvy()
{
  DLCharacterProfile profile;
  profile.directDiffuseEnabled = true;
  profile.directDiffuseStepSharpness = 0.75;
  profile.directDiffusePbrBlend = 0.25;
  profile.directDiffuseWrap = 0.5;
  profile.directDiffuseNormalization = 1.0;
  profile.referenceTint = vec3(0.321569, 0.388235, 0.176471);
  profile.outlineEnabled = true;
  profile.outlineColor = vec3(0.164706, 0.054902, 0.054902);
  return profile;
}

DLCharacterProfile dlBuiltInCharacterProfile(int characterId)
{
  if (characterId == DL_CHARACTER_IVY)
  {
    return dlCharacterProfileIvy();
  }

  // Callers handle Custom separately. This is a deterministic fallback.
  return dlCharacterProfileIvy();
}
// END GENERATED CHARACTER PROFILES

//: state cull_face on
//: state blend none

//: param custom {
//:   "default": 0,
//:   "label": "Outline Color",
//:   "widget": "color",
//:   "group": "Deadlimit Outline"
//: }
uniform vec3 dl_outline_color;

//: param custom {
//:   "default": 0,
//:   "label": "Character",
//:   "widget": "combobox",
//:   "values": {
// BEGIN GENERATED CHARACTER SELECTOR
//:     "Custom": 0,
//:     "Ivy": 1
// END GENERATED CHARACTER SELECTOR
//:   },
//:   "group": "Deadlimit Outline"
//: }
uniform int dl_outline_character;

//: param custom {
//:   "default": true,
//:   "label": "Use Character Color",
//:   "group": "Deadlimit Outline"
//: }
uniform bool dl_outline_use_character_color;

void shade(V2F inputs)
{
  vec3 outlineColor = dl_outline_color;
  if (dl_outline_character != DL_CHARACTER_CUSTOM && dl_outline_use_character_color)
  {
    outlineColor = dlBuiltInCharacterProfile(dl_outline_character).outlineColor;
  }

  albedoOutput(vec3(0.0));
  diffuseShadingOutput(vec3(0.0));
  specularShadingOutput(vec3(0.0));
  emissiveColorOutput(outlineColor);
  sssCoefficientsOutput(vec4(0.0));
}
