// Deadlimit Shade — preview-only inverted-hull shell shader for Substance 3D Painter.
//
// The preview mesh generator owns shell geometry and Outline Width.
// Expected prototype contract:
//   - duplicate preview shell
//   - offset shell vertices outward
//   - reverse shell triangle winding
//   - assign preview-only material: __deadlimit_outline
//
// This shader only shades the already-generated shell.

// BEGIN GENERATED CHARACTER PROFILES
// Generated by tools/Generate-CharacterProfiles.ps1. Do not edit by hand.
// Source of truth: profiles/*.json.

const int DL_CHARACTER_CUSTOM = 0;
const int DL_CHARACTER_IVY = 1;

struct DLCharacterProfile
{
  bool directDiffuseEnabled;
  float directDiffuseSteps;
  float directDiffuseStepSharpness;
  float directDiffusePbrBlend;
  float directDiffuseWrap;
  float directDiffuseNormalization;
  bool bounceLightingEnabled;
  vec2 bounceDiffuseRange;
  vec2 bounceDfaoInfluenceRange;
  vec3 bounceLightWeights;
  bool bounceExposureControlEnabled;
  vec3 bounceExposureTargets;
  float bounceExposurePbrBlend;
  vec3 bounceProbePositiveX;
  vec3 bounceProbePositiveY;
  vec3 bounceProbePositiveZ;
  vec3 bounceProbeNegativeX;
  vec3 bounceProbeNegativeY;
  vec3 bounceProbeNegativeZ;
  float bounceAmbientFloor;
  float bounceTransmissiveStrength;
  float bounceAoStrength;
  bool directSpecularEnabled;
  float directSpecularSteps;
  float directSpecularStepSharpness;
  float directSpecularTint;
  float directSpecularRoughnessBias;
  float directSpecularReflectance;
  bool rimEnabled;
  float rimCutoff;
  float rimSharpness;
  float rimStrength;
  vec2 rimUpRamp;
  vec3 keyLightDirection;
  vec3 keyLightColor;
  float keyLightIntensity;
  vec3 fillLightDirection;
  vec3 fillLightColor;
  float fillLightIntensity;
  vec3 environmentColor;
  float environmentDiffuse;
  vec3 referenceTint;
  bool outlineEnabled;
  vec3 outlineColor;
  vec3 outlineAdditive;
  float outlineMask;
  float outlineVertexColorTint;
};

DLCharacterProfile dlCharacterProfileIvy()
{
  DLCharacterProfile profile;
  profile.directDiffuseEnabled = true;
  profile.directDiffuseSteps = 2.0;
  profile.directDiffuseStepSharpness = 0.9;
  profile.directDiffusePbrBlend = 0.25;
  profile.directDiffuseWrap = 0.8;
  profile.directDiffuseNormalization = 0.625;
  profile.bounceLightingEnabled = true;
  profile.bounceDiffuseRange = vec2(-1.0, 1.0);
  profile.bounceDfaoInfluenceRange = vec2(0.4, 1.0);
  profile.bounceLightWeights = vec3(0.42, 0.42, 0.126);
  profile.bounceExposureControlEnabled = true;
  profile.bounceExposureTargets = vec3(1.0, 0.5, 0.1);
  profile.bounceExposurePbrBlend = 0.5;
  profile.bounceProbePositiveX = vec3(1.0644531, 1.0644531, 1.0644531);
  profile.bounceProbePositiveY = vec3(0.9052734, 0.9052734, 0.9052734);
  profile.bounceProbePositiveZ = vec3(1.4628906, 1.4628906, 1.4628906);
  profile.bounceProbeNegativeX = vec3(0.5595703, 0.5595703, 0.5595703);
  profile.bounceProbeNegativeY = vec3(0.5546875, 0.5546875, 0.5546875);
  profile.bounceProbeNegativeZ = vec3(0.199707, 0.199707, 0.199707);
  profile.bounceAmbientFloor = 0.18;
  profile.bounceTransmissiveStrength = 1.0;
  profile.bounceAoStrength = 0.55;
  profile.directSpecularEnabled = false;
  profile.directSpecularSteps = 3.0;
  profile.directSpecularStepSharpness = 0.55;
  profile.directSpecularTint = 0.35;
  profile.directSpecularRoughnessBias = 0.18;
  profile.directSpecularReflectance = 0.025;
  profile.rimEnabled = true;
  profile.rimCutoff = 1.0;
  profile.rimSharpness = 0.01;
  profile.rimStrength = 0.3;
  profile.rimUpRamp = vec2(0.0, 1.0);
  profile.keyLightDirection = vec3(0.494, 0.766, -0.411);
  profile.keyLightColor = vec3(1.0, 1.0, 1.0);
  profile.keyLightIntensity = 1.6;
  profile.fillLightDirection = vec3(-0.693, 0.071, 0.719);
  profile.fillLightColor = vec3(1.0, 1.0, 1.0);
  profile.fillLightIntensity = 0.0;
  profile.environmentColor = vec3(0.827451, 0.886275, 0.972549);
  profile.environmentDiffuse = 0.22;
  profile.referenceTint = vec3(0.321569, 0.388235, 0.176471);
  profile.outlineEnabled = true;
  profile.outlineColor = vec3(0.164706, 0.054902, 0.054902);
  profile.outlineAdditive = vec3(0.243137, 0.164706, 0.164706);
  profile.outlineMask = 0.819;
  profile.outlineVertexColorTint = 0.0;
  return profile;
}

DLCharacterProfile dlBuiltInCharacterProfile(int characterId)
{
  if (characterId == DL_CHARACTER_IVY)
  {
    return dlCharacterProfileIvy();
  }

  // Callers handle Custom separately. This is a deterministic fallback.
  return dlCharacterProfileIvy();
}
// END GENERATED CHARACTER PROFILES

//: state cull_face on
// CSDK S_MODE_OUTLINE uses dual-source blending:
//   out0 + framebuffer * out1
// Painter's add_multiply state exposes that composition through color1Output.
//: state blend add_multiply

//: param custom {
//:   "default": 0,
//:   "label": "Outline Color",
//:   "widget": "color",
//:   "group": "Deadlimit Outline"
//: }
uniform vec3 dl_outline_color;

//: param custom {
//:   "default": 0,
//:   "label": "Outline Additive",
//:   "widget": "color",
//:   "group": "Deadlimit Outline"
//: }
uniform vec3 dl_outline_additive;

//: param custom {
//:   "default": 1.0,
//:   "label": "Outline Mask",
//:   "min": 0.0,
//:   "max": 1.0,
//:   "group": "Deadlimit Outline"
//: }
uniform float dl_outline_mask;

//: param custom {
//:   "default": 0,
//:   "label": "Character",
//:   "widget": "combobox",
//:   "values": {
// BEGIN GENERATED CHARACTER SELECTOR
//:     "Custom": 0,
//:     "Ivy": 1
// END GENERATED CHARACTER SELECTOR
//:   },
//:   "group": "Deadlimit Outline"
//: }
uniform int dl_outline_character;

//: param custom {
//:   "default": true,
//:   "label": "Use Character Color",
//:   "group": "Deadlimit Outline"
//: }
uniform bool dl_outline_use_character_color;

void shade(V2F inputs)
{
  vec3 outlineColor = dl_outline_color;
  vec3 outlineAdditive = dl_outline_additive;
  float outlineMask = dl_outline_mask;
  if (dl_outline_character != DL_CHARACTER_CUSTOM && dl_outline_use_character_color)
  {
    DLCharacterProfile profile = dlBuiltInCharacterProfile(dl_outline_character);
    outlineColor = profile.outlineColor;
    outlineAdditive = profile.outlineAdditive;
    outlineMask = profile.outlineMask;
  }

  vec3 sourceAdditive = mix(vec3(0.0), outlineAdditive, vec3(outlineMask));
  vec3 destinationTint = mix(vec3(1.0), outlineColor, vec3(outlineMask));
  albedoOutput(outlineColor);
  diffuseShadingOutput(sourceAdditive);
  specularShadingOutput(vec3(0.0));
  emissiveColorOutput(vec3(0.0));
  alphaOutput(1.0);
  color1Output(vec4(destinationTint, 1.0));
  sssCoefficientsOutput(vec4(0.0));
}
