// Deadlimit Shade — Deadlock hero material bootstrap for Substance 3D Painter.
//
// The common metal/rough baseline is extended with the statically recovered Deadlock
// NPR direct-diffuse equation. Runtime globals that have not been captured remain
// explicit calibration controls and are not presented as retail defaults.

import lib-sss.glsl
import lib-pbr.glsl
import lib-emissive.glsl
import lib-pom.glsl
import lib-utils.glsl

// Retail preview textures use ordinary sampler2D resources and must remain
// valid for the whole mesh while Painter is painting another Texture Set.
// Painter otherwise applies its local sampling optimization and can display
// saturated cyan/blue tiles outside the currently active set.
//: state nonlocal on

// BEGIN GENERATED CHARACTER PROFILES
// Generated by tools/Generate-CharacterProfiles.ps1. Do not edit by hand.
// Source of truth: profiles/*.json.

const int DL_CHARACTER_CUSTOM = 0;
const int DL_CHARACTER_IVY = 1;

struct DLCharacterProfile
{
  bool directDiffuseEnabled;
  float directDiffuseStepSharpness;
  float directDiffusePbrBlend;
  float directDiffuseWrap;
  float directDiffuseNormalization;
  bool directSpecularEnabled;
  float directSpecularIntensity;
  float directSpecularRoughnessScale;
  float directSpecularThreshold;
  float directSpecularSoftness;
  bool rimLightingEnabled;
  vec3 rimLightingColor;
  float rimLightingIntensity;
  float rimLightingPower;
  float rimLightingThreshold;
  float rimLightingSoftness;
  vec3 keyLightDirection;
  vec3 keyLightColor;
  float keyLightIntensity;
  float environmentDiffuse;
  float environmentSpecular;
  vec3 referenceTint;
  bool outlineEnabled;
  vec3 outlineColor;
};

DLCharacterProfile dlCharacterProfileIvy()
{
  DLCharacterProfile profile;
  profile.directDiffuseEnabled = true;
  profile.directDiffuseStepSharpness = 0.78;
  profile.directDiffusePbrBlend = 0.08;
  profile.directDiffuseWrap = 0.52;
  profile.directDiffuseNormalization = 0.95;
  profile.directSpecularEnabled = true;
  profile.directSpecularIntensity = 0.55;
  profile.directSpecularRoughnessScale = 0.65;
  profile.directSpecularThreshold = 0.18;
  profile.directSpecularSoftness = 0.06;
  profile.rimLightingEnabled = true;
  profile.rimLightingColor = vec3(0.44, 0.58, 0.78);
  profile.rimLightingIntensity = 0.38;
  profile.rimLightingPower = 2.4;
  profile.rimLightingThreshold = 0.32;
  profile.rimLightingSoftness = 0.12;
  profile.keyLightDirection = vec3(0.35, 0.6, 0.72);
  profile.keyLightColor = vec3(1.0, 0.88, 0.72);
  profile.keyLightIntensity = 1.15;
  profile.environmentDiffuse = 0.22;
  profile.environmentSpecular = 0.28;
  profile.referenceTint = vec3(0.321569, 0.388235, 0.176471);
  profile.outlineEnabled = true;
  profile.outlineColor = vec3(0.164706, 0.054902, 0.054902);
  return profile;
}

DLCharacterProfile dlBuiltInCharacterProfile(int characterId)
{
  if (characterId == DL_CHARACTER_IVY)
  {
    return dlCharacterProfileIvy();
  }

  // Callers handle Custom separately. This is a deterministic fallback.
  return dlCharacterProfileIvy();
}
// END GENERATED CHARACTER PROFILES

//: param auto channel_basecolor
uniform SamplerSparse basecolor_tex;

//: param auto channel_roughness
uniform SamplerSparse roughness_tex;

//: param auto channel_metallic
uniform SamplerSparse metallic_tex;

//: param auto channel_specularlevel
uniform SamplerSparse specularlevel_tex;

// Optional default-character preview maps. They are decoded locally from the
// artist's Deadlimit 0source extraction or its recorded read-only retail VPK.
// They bypass Painter channels only on the dedicated Valve Texture Sets.
//: param custom {
//:   "default": false,
//:   "label": "Use Default Retail Inputs",
//:   "group": "Deadlimit Retail Preview"
//: }
uniform bool dl_use_retail_inputs;

//: param custom { "default": "", "default_color": [1.0, 1.0, 1.0, 1.0], "label": "Color + Metalness", "usage": "texture", "group": "Deadlimit Retail Preview" }
uniform sampler2D dl_retail_color;

// ValveResourceFormat presents the packed retail normal as decoded tangent
// normal RGB and the processed roughness as A.
//: param custom { "default": "", "default_color": [0.5, 0.5, 1.0, 0.5], "label": "Normal + Roughness", "usage": "texture", "group": "Deadlimit Retail Preview" }
uniform sampler2D dl_retail_normal_roughness;

//: param custom { "default": "", "default_color": [1.0, 1.0, 1.0, 1.0], "label": "Ambient Occlusion", "usage": "texture", "group": "Deadlimit Retail Preview" }
uniform sampler2D dl_retail_ambient_occlusion;

//: param custom {
//:   "default": 0,
//:   "label": "Character",
//:   "widget": "combobox",
//:   "values": {
// BEGIN GENERATED CHARACTER SELECTOR
//:     "Custom": 0,
//:     "Ivy": 1
// END GENERATED CHARACTER SELECTOR
//:   },
//:   "group": "Deadlimit Character"
//: }
uniform int dl_character;

//: param custom {
//:   "default": false,
//:   "label": "Use Custom Calibration",
//:   "group": "Deadlimit Character",
//:   "description": "Use the calibration controls below instead of the selected character profile values."
//: }
uniform bool dl_use_custom_calibration;

//: param custom {
//:   "default": false,
//:   "label": "NPR Direct Diffuse",
//:   "group": "Deadlimit NPR Calibration"
//: }
uniform bool dl_npr_direct_diffuse;

//: param custom {
//:   "default": 0.75,
//:   "label": "Diffuse Step Sharpness",
//:   "min": 0.0,
//:   "max": 0.95,
//:   "group": "Deadlimit NPR Calibration"
//: }
uniform float dl_npr_diffuse_step_sharpness;

//: param custom {
//:   "default": 0.25,
//:   "label": "Diffuse PBR Blend",
//:   "min": 0.0,
//:   "max": 1.0,
//:   "group": "Deadlimit NPR Calibration"
//: }
uniform float dl_npr_diffuse_pbr_blend;

//: param custom {
//:   "default": 0.5,
//:   "label": "Direct Light Wrap",
//:   "min": 0.0,
//:   "max": 1.0,
//:   "group": "Deadlimit NPR Calibration"
//: }
uniform float dl_npr_direct_light_wrap;

//: param custom {
//:   "default": 1.0,
//:   "label": "Direct Light Normalization",
//:   "min": 0.0,
//:   "max": 4.0,
//:   "group": "Deadlimit NPR Calibration"
//: }
uniform float dl_npr_direct_light_normalization;

// The direct-specular and rim controls below are Painter calibration values.
// Static retail evidence confirms separate NPR paths, while their runtime
// control values remain unresolved.
//: param custom { "default": true, "label": "NPR Direct Specular", "group": "Deadlimit NPR Calibration" }
uniform bool dl_npr_direct_specular;

//: param custom { "default": 0.55, "label": "Direct Specular Intensity", "min": 0.0, "max": 4.0, "group": "Deadlimit NPR Calibration" }
uniform float dl_npr_direct_specular_intensity;

//: param custom { "default": 0.65, "label": "Specular Roughness Scale", "min": 0.0, "max": 2.0, "group": "Deadlimit NPR Calibration" }
uniform float dl_npr_direct_specular_roughness_scale;

//: param custom { "default": 0.18, "label": "Specular Step Threshold", "min": 0.0, "max": 1.0, "group": "Deadlimit NPR Calibration" }
uniform float dl_npr_direct_specular_threshold;

//: param custom { "default": 0.06, "label": "Specular Step Softness", "min": 0.001, "max": 0.5, "group": "Deadlimit NPR Calibration" }
uniform float dl_npr_direct_specular_softness;

//: param custom { "default": true, "label": "NPR Rim Lighting", "group": "Deadlimit NPR Calibration" }
uniform bool dl_npr_rim_lighting;

//: param custom { "default": [0.44, 0.58, 0.78], "label": "Rim Color", "widget": "color", "group": "Deadlimit NPR Calibration" }
uniform vec3 dl_npr_rim_color;

//: param custom { "default": 0.38, "label": "Rim Intensity", "min": 0.0, "max": 4.0, "group": "Deadlimit NPR Calibration" }
uniform float dl_npr_rim_intensity;

//: param custom { "default": 2.4, "label": "Rim Power", "min": 0.1, "max": 12.0, "group": "Deadlimit NPR Calibration" }
uniform float dl_npr_rim_power;

//: param custom { "default": 0.32, "label": "Rim Step Threshold", "min": 0.0, "max": 1.0, "group": "Deadlimit NPR Calibration" }
uniform float dl_npr_rim_threshold;

//: param custom { "default": 0.12, "label": "Rim Step Softness", "min": 0.001, "max": 0.5, "group": "Deadlimit NPR Calibration" }
uniform float dl_npr_rim_softness;

//: param custom {
//:   "default": [0.35, 0.6, 0.72],
//:   "label": "Key Light Direction",
//:   "min": -1.0,
//:   "max": 1.0,
//:   "group": "Deadlimit Preview Lighting",
//:   "description": "World-space direction from the surface toward the preview key light."
//: }
uniform vec3 dl_key_light_direction;

//: param custom {
//:   "default": [1.0, 0.95, 0.9],
//:   "label": "Key Light Color",
//:   "widget": "color",
//:   "group": "Deadlimit Preview Lighting"
//: }
uniform vec3 dl_key_light_color;

//: param custom {
//:   "default": 0.75,
//:   "label": "Key Light Intensity",
//:   "min": 0.0,
//:   "max": 4.0,
//:   "group": "Deadlimit Preview Lighting"
//: }
uniform float dl_key_light_intensity;

//: param custom {
//:   "default": 0.65,
//:   "label": "Environment Diffuse",
//:   "min": 0.0,
//:   "max": 2.0,
//:   "group": "Deadlimit Preview Lighting"
//: }
uniform float dl_environment_diffuse;

//: param custom {
//:   "default": 0.28,
//:   "label": "Environment Specular",
//:   "min": 0.0,
//:   "max": 2.0,
//:   "group": "Deadlimit Preview Lighting"
//: }
uniform float dl_environment_specular;

//: param custom {
//:   "default": 0.0,
//:   "label": "Vertex Color Multiply",
//:   "min": 0.0,
//:   "max": 1.0,
//:   "group": "Deadlimit Retail Preview",
//:   "description": "VMAT-driven color0 multiplication. Apply Deadlimit configures this from F_VERTEX_COLOR and g_fVertexColorStrength1."
//: }
uniform float dl_vertex_color_multiply;

//: param custom {
//:   "default": 0,
//:   "label": "Lighting Inputs",
//:   "widget": "combobox",
//:   "values": {
//:     "Material / Retail": 0,
//:     "Diagnostic Neutral": 1
//:   },
//:   "group": "Deadlimit Diagnostics"
//: }
uniform int dl_lighting_input_mode;

//: param custom {
//:   "default": 0,
//:   "label": "Debug View",
//:   "widget": "combobox",
//:   "values": {
//:     "Shaded": 0,
//:     "Base Color": 1,
//:     "Roughness": 2,
//:     "Metallic": 3,
//:     "Ambient Occlusion": 4,
//:     "Vertex Color RGB": 5,
//:     "Vertex Color Alpha": 6,
//:     "N dot L (Signed)": 7,
//:     "Wrapped Direct Diffuse": 8,
//:     "Quantized Direct Diffuse": 9,
//:     "Final Direct Diffuse": 10,
//:     "Character Profile": 11,
//:     "Direct Specular": 12,
//:     "Rim Contribution": 13,
//:     "NPR Lighting Composite": 14,
//:     "Painter PBR Baseline": 15
//:   },
//:   "group": "Deadlimit Diagnostics"
//: }
uniform int dl_debug_view;

struct DLDirectDiffuseSample
{
  float ndotl;
  float lambert;
  float wrapped;
  float quantized;
  float finalValue;
};

struct DLDirectSpecularSample
{
  float rawLobe;
  float steppedLobe;
  vec3 contribution;
};

struct DLRimSample
{
  float rawRim;
  float steppedRim;
  vec3 contribution;
};

DLCharacterProfile dlCustomCharacterProfile()
{
  DLCharacterProfile profile;
  profile.directDiffuseEnabled = dl_npr_direct_diffuse;
  profile.directDiffuseStepSharpness = dl_npr_diffuse_step_sharpness;
  profile.directDiffusePbrBlend = dl_npr_diffuse_pbr_blend;
  profile.directDiffuseWrap = dl_npr_direct_light_wrap;
  profile.directDiffuseNormalization = dl_npr_direct_light_normalization;
  profile.directSpecularEnabled = dl_npr_direct_specular;
  profile.directSpecularIntensity = dl_npr_direct_specular_intensity;
  profile.directSpecularRoughnessScale = dl_npr_direct_specular_roughness_scale;
  profile.directSpecularThreshold = dl_npr_direct_specular_threshold;
  profile.directSpecularSoftness = dl_npr_direct_specular_softness;
  profile.rimLightingEnabled = dl_npr_rim_lighting;
  profile.rimLightingColor = dl_npr_rim_color;
  profile.rimLightingIntensity = dl_npr_rim_intensity;
  profile.rimLightingPower = dl_npr_rim_power;
  profile.rimLightingThreshold = dl_npr_rim_threshold;
  profile.rimLightingSoftness = dl_npr_rim_softness;
  profile.keyLightDirection = dl_key_light_direction;
  profile.keyLightColor = dl_key_light_color;
  profile.keyLightIntensity = dl_key_light_intensity;
  profile.environmentDiffuse = dl_environment_diffuse;
  profile.environmentSpecular = dl_environment_specular;
  profile.referenceTint = vec3(0.18);
  profile.outlineEnabled = true;
  profile.outlineColor = vec3(0.08, 0.02, 0.02);
  return profile;
}

DLCharacterProfile dlActiveCharacterProfile()
{
  if (dl_character == DL_CHARACTER_CUSTOM || dl_use_custom_calibration)
  {
    return dlCustomCharacterProfile();
  }

  return dlBuiltInCharacterProfile(dl_character);
}

float dlNprQuantize(float value, float sharpness)
{
  float safeSharpness = clamp(sharpness, 0.0, 0.95);
  float base = floor(value);
  float fraction = fract(value);
  float wing = fraction > 0.5 ? 1.0 - fraction : fraction;
  float exponent = 1.0 / (1.0 - safeSharpness);

  // Algebraically equivalent to pow(0.5, 1.0 - exponent) * pow(wing, exponent),
  // with stable behavior as sharpness approaches its supported upper bound.
  float shapedWing = 0.5 * pow(2.0 * wing, exponent);
  return base + (fraction > 0.5 ? 1.0 - shapedWing : shapedWing);
}

vec3 dlKeyLightDirection(DLCharacterProfile profile)
{
  float lightLengthSquared = dot(profile.keyLightDirection, profile.keyLightDirection);
  return lightLengthSquared > 0.000001
    ? normalize(profile.keyLightDirection)
    : vec3(0.0, 1.0, 0.0);
}

DLDirectDiffuseSample dlEvaluateDirectDiffuse(vec3 normal, DLCharacterProfile profile)
{
  DLDirectDiffuseSample sample;
  vec3 lightDirection = dlKeyLightDirection(profile);

  sample.ndotl = dot(normal, lightDirection);
  sample.lambert = max(sample.ndotl, 0.0);
  sample.wrapped = clamp(
    0.5 + 2.0 * ((profile.directDiffuseWrap - 0.5) + sample.ndotl - 0.5),
    0.0,
    1.0);
  sample.quantized = dlNprQuantize(
    sample.wrapped,
    profile.directDiffuseStepSharpness);

  float nprResponse = profile.directDiffuseNormalization * sample.quantized;
  sample.finalValue = profile.directDiffuseEnabled
    ? mix(nprResponse, sample.lambert, clamp(profile.directDiffusePbrBlend, 0.0, 1.0))
    : sample.lambert;
  return sample;
}

DLDirectSpecularSample dlEvaluateDirectSpecular(
  vec3 normal,
  vec3 viewDirection,
  float roughness,
  vec3 specularColor,
  DLCharacterProfile profile)
{
  DLDirectSpecularSample sample;
  vec3 lightDirection = dlKeyLightDirection(profile);
  vec3 halfVectorInput = lightDirection + viewDirection;
  vec3 halfVector = dot(halfVectorInput, halfVectorInput) > 0.000001
    ? normalize(halfVectorInput)
    : normal;
  float adjustedRoughness = clamp(
    roughness * profile.directSpecularRoughnessScale,
    0.04,
    1.0);
  float exponent = clamp(2.0 / (adjustedRoughness * adjustedRoughness) - 2.0, 2.0, 128.0);
  float ndoth = max(dot(normal, halfVector), 0.0);
  float ndotl = max(dot(normal, lightDirection), 0.0);
  sample.rawLobe = pow(ndoth, exponent) * ndotl;
  float softness = max(profile.directSpecularSoftness, 0.001);
  sample.steppedLobe = smoothstep(
    profile.directSpecularThreshold - softness,
    profile.directSpecularThreshold + softness,
    sample.rawLobe);
  vec3 reflectanceTint = mix(vec3(1.0), specularColor, 0.55);
  sample.contribution = profile.directSpecularEnabled
    ? profile.keyLightIntensity * profile.keyLightColor *
      profile.directSpecularIntensity * sample.steppedLobe * reflectanceTint
    : vec3(0.0);
  return sample;
}

DLRimSample dlEvaluateRim(
  vec3 normal,
  vec3 viewDirection,
  DLCharacterProfile profile)
{
  DLRimSample sample;
  float viewFacing = clamp(dot(normal, viewDirection), 0.0, 1.0);
  sample.rawRim = pow(1.0 - viewFacing, max(profile.rimLightingPower, 0.1));
  float softness = max(profile.rimLightingSoftness, 0.001);
  sample.steppedRim = smoothstep(
    profile.rimLightingThreshold - softness,
    profile.rimLightingThreshold + softness,
    sample.rawRim);
  float awayFromKey = 1.0 - max(dot(normal, dlKeyLightDirection(profile)), 0.0);
  sample.contribution = profile.rimLightingEnabled
    ? profile.rimLightingColor * profile.rimLightingIntensity *
      sample.steppedRim * mix(0.45, 1.0, awayFromKey)
    : vec3(0.0);
  return sample;
}

void dlDebugOutput(vec3 value)
{
  albedoOutput(vec3(0.0));
  diffuseShadingOutput(vec3(0.0));
  specularShadingOutput(vec3(0.0));
  emissiveColorOutput(value);
  sssCoefficientsOutput(vec4(0.0));
}

void shade(V2F inputs)
{
  // Keep the bootstrap path aligned with Painter's current official metal/rough
  // reference shader before adding any Deadlock-specific transformation.
  vec3 viewTS = worldSpaceToTangentSpace(getEyeVec(inputs.position), inputs);
  applyParallaxOffset(inputs, viewTS);

  float roughness = getRoughness(roughness_tex, inputs.sparse_coord);
  vec3 baseColor = getBaseColor(basecolor_tex, inputs.sparse_coord);
  float metallic = getMetallic(metallic_tex, inputs.sparse_coord);
  float specularLevel = getSpecularLevel(specularlevel_tex, inputs.sparse_coord);
  float ambientOcclusion = getAO(inputs.sparse_coord);
  vec3 retailNormal = vec3(0.0, 0.0, 1.0);
  if (dl_use_retail_inputs)
  {
    vec4 retailColorMetalness = texture(dl_retail_color, inputs.tex_coord);
    vec4 retailNormalRoughness = texture(dl_retail_normal_roughness, inputs.tex_coord);
    baseColor = retailColorMetalness.rgb;
    metallic = retailColorMetalness.a;
    retailNormal = normalUnpack(retailNormalRoughness);
    roughness = retailNormalRoughness.a;
    ambientOcclusion = texture(dl_retail_ambient_occlusion, inputs.tex_coord).r;
  }

  vec3 vertexColor = clamp(inputs.color[0].rgb, vec3(0.0), vec3(1.0));
  float vertexAlpha = clamp(inputs.color[0].a, 0.0, 1.0);
  DLCharacterProfile characterProfile = dlActiveCharacterProfile();
  bool diagnosticInputs = dl_lighting_input_mode == 1;
  LocalVectors vectors = dl_use_retail_inputs && !diagnosticInputs
    ? computeLocalFrame(inputs, tangentSpaceToWorldSpace(retailNormal, inputs), 0.0)
    : computeLocalFrame(inputs);

  if (diagnosticInputs)
  {
    baseColor = vec3(0.42, 0.46, 0.52);
    roughness = 0.48;
    metallic = 0.0;
    specularLevel = 0.5;
    ambientOcclusion = 1.0;
  }

  DLDirectDiffuseSample directDiffuse = dlEvaluateDirectDiffuse(
    vectors.normal,
    characterProfile);

  // VMAT vertex color is part of the resolved material Base Color. Apply it
  // before diagnostics so Deadlimit View -> Base Color and shaded rendering
  // show the same eyes and other vertex-colored slots.
  if (!diagnosticInputs)
  {
    baseColor *= mix(vec3(1.0), vertexColor, dl_vertex_color_multiply);
  }

  if (dl_debug_view == 1)
  {
    dlDebugOutput(baseColor);
    return;
  }
  if (dl_debug_view == 2)
  {
    dlDebugOutput(vec3(roughness));
    return;
  }
  if (dl_debug_view == 3)
  {
    dlDebugOutput(vec3(metallic));
    return;
  }
  if (dl_debug_view == 4)
  {
    dlDebugOutput(vec3(ambientOcclusion));
    return;
  }
  if (dl_debug_view == 5)
  {
    dlDebugOutput(vertexColor);
    return;
  }
  if (dl_debug_view == 6)
  {
    dlDebugOutput(vec3(vertexAlpha));
    return;
  }
  if (dl_debug_view == 7)
  {
    dlDebugOutput(vec3(0.5 + 0.5 * directDiffuse.ndotl));
    return;
  }
  if (dl_debug_view == 8)
  {
    dlDebugOutput(vec3(directDiffuse.wrapped));
    return;
  }
  if (dl_debug_view == 9)
  {
    dlDebugOutput(vec3(directDiffuse.quantized));
    return;
  }
  if (dl_debug_view == 10)
  {
    dlDebugOutput(vec3(directDiffuse.finalValue));
    return;
  }
  if (dl_debug_view == 11)
  {
    dlDebugOutput(characterProfile.referenceTint);
    return;
  }

  vec3 diffColor = generateDiffuseColor(baseColor, metallic);
  vec3 specColor = generateSpecularColor(specularLevel, baseColor, metallic);
  vec3 viewDirection = normalize(getEyeVec(inputs.position));
  DLDirectSpecularSample directSpecular = dlEvaluateDirectSpecular(
    vectors.normal,
    viewDirection,
    roughness,
    specColor,
    characterProfile);
  DLRimSample rim = dlEvaluateRim(
    vectors.normal,
    viewDirection,
    characterProfile);

  float occlusion = ambientOcclusion * getShadowFactor();
  float specOcclusion = specularOcclusionCorrection(occlusion, metallic, roughness);

  vec3 diffuseLighting =
    characterProfile.environmentDiffuse * envIrradiance(vectors.normal) +
    characterProfile.keyLightIntensity * characterProfile.keyLightColor * directDiffuse.finalValue;
  vec3 environmentSpecular = characterProfile.environmentSpecular *
    pbrComputeSpecular(vectors, specColor, roughness);
  vec3 nprLightingComposite =
    diffColor * occlusion * diffuseLighting +
    specOcclusion * environmentSpecular +
    directSpecular.contribution +
    ambientOcclusion * rim.contribution;

  if (dl_debug_view == 12)
  {
    dlDebugOutput(directSpecular.contribution);
    return;
  }
  if (dl_debug_view == 13)
  {
    dlDebugOutput(rim.contribution);
    return;
  }
  if (dl_debug_view == 14)
  {
    dlDebugOutput(nprLightingComposite);
    return;
  }
  if (dl_debug_view == 15)
  {
    emissiveColorOutput(pbrComputeEmissive(emissive_tex, inputs.sparse_coord));
    albedoOutput(diffColor);
    diffuseShadingOutput(occlusion * envIrradiance(vectors.normal));
    specularShadingOutput(specOcclusion * pbrComputeSpecular(vectors, specColor, roughness));
    sssCoefficientsOutput(getSSSCoefficients(inputs.sparse_coord));
    return;
  }

  emissiveColorOutput(pbrComputeEmissive(emissive_tex, inputs.sparse_coord));
  albedoOutput(diffColor);
  diffuseShadingOutput(occlusion * diffuseLighting);
  specularShadingOutput(
    specOcclusion * environmentSpecular +
    directSpecular.contribution +
    ambientOcclusion * rim.contribution);
  sssCoefficientsOutput(getSSSCoefficients(inputs.sparse_coord));
}
