[CmdletBinding()]
param(
    [string] $ProfilesPath = (Join-Path $PSScriptRoot '..\profiles'),
    [string[]] $ShaderPaths = @(
        (Join-Path $PSScriptRoot '..\shaders\Deadlock_Hero.glsl'),
        (Join-Path $PSScriptRoot '..\shaders\Deadlock_Outline.glsl')
    )
)

$ErrorActionPreference = 'Stop'
$culture = [System.Globalization.CultureInfo]::InvariantCulture

function Format-GlslFloat {
    param([double] $Value)

    $text = $Value.ToString('0.0######', $culture)
    if ($text -notmatch '\.') {
        $text += '.0'
    }
    return $text
}

function Format-GlslBool {
    param([bool] $Value)

    if ($Value) { return 'true' }
    return 'false'
}

function Format-GlslVec3 {
    param($Values)

    if (@($Values).Count -ne 3) {
        throw 'Expected exactly three values for a GLSL vec3.'
    }

    $parts = @($Values | ForEach-Object { Format-GlslFloat ([double] $_) })
    return "vec3($($parts -join ', '))"
}

$profileFiles = Get-ChildItem -LiteralPath $ProfilesPath -Filter '*.json' -File |
    Where-Object { $_.Name -ne 'schema.json' } |
    Sort-Object Name

$profiles = @($profileFiles | ForEach-Object {
    $profile = Get-Content -LiteralPath $_.FullName -Raw | ConvertFrom-Json
    if ($profile.schemaVersion -ne 1) {
        throw "Unsupported profile schema version in $($_.FullName)."
    }
    if ($profile.id -lt 1) {
        throw "Profile IDs must be positive; 0 is reserved for Custom: $($_.FullName)."
    }
    $profile
})

$duplicateId = $profiles | Group-Object id | Where-Object Count -gt 1
$duplicateKey = $profiles | Group-Object key | Where-Object Count -gt 1
if ($duplicateId) { throw "Duplicate character profile ID: $($duplicateId.Name)" }
if ($duplicateKey) { throw "Duplicate character profile key: $($duplicateKey.Name)" }

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('// Generated by tools/Generate-CharacterProfiles.ps1. Do not edit by hand.')
$lines.Add('// Source of truth: profiles/*.json.')
$lines.Add('')
$lines.Add('const int DL_CHARACTER_CUSTOM = 0;')
foreach ($profile in ($profiles | Sort-Object id)) {
    $constant = 'DL_CHARACTER_' + ([string] $profile.key).ToUpperInvariant()
    $lines.Add("const int $constant = $($profile.id);")
}
$lines.Add('')
$lines.Add('struct DLCharacterProfile')
$lines.Add('{')
$lines.Add('  bool directDiffuseEnabled;')
$lines.Add('  float directDiffuseStepSharpness;')
$lines.Add('  float directDiffusePbrBlend;')
$lines.Add('  float directDiffuseWrap;')
$lines.Add('  float directDiffuseNormalization;')
$lines.Add('  vec3 referenceTint;')
$lines.Add('  bool outlineEnabled;')
$lines.Add('  vec3 outlineColor;')
$lines.Add('};')
$lines.Add('')

foreach ($profile in ($profiles | Sort-Object id)) {
    $functionSuffix = ([string] $profile.key).Substring(0, 1).ToUpperInvariant() + ([string] $profile.key).Substring(1)
    $lines.Add("DLCharacterProfile dlCharacterProfile$functionSuffix()")
    $lines.Add('{')
    $lines.Add('  DLCharacterProfile profile;')
    $lines.Add("  profile.directDiffuseEnabled = $(Format-GlslBool ([bool] $profile.directDiffuse.enabled));")
    $lines.Add("  profile.directDiffuseStepSharpness = $(Format-GlslFloat ([double] $profile.directDiffuse.stepSharpness));")
    $lines.Add("  profile.directDiffusePbrBlend = $(Format-GlslFloat ([double] $profile.directDiffuse.pbrBlend));")
    $lines.Add("  profile.directDiffuseWrap = $(Format-GlslFloat ([double] $profile.directDiffuse.wrap));")
    $lines.Add("  profile.directDiffuseNormalization = $(Format-GlslFloat ([double] $profile.directDiffuse.normalization));")
    $lines.Add("  profile.referenceTint = $(Format-GlslVec3 $profile.referenceTint);")
    $lines.Add("  profile.outlineEnabled = $(Format-GlslBool ([bool] $profile.outline.enabled));")
    $lines.Add("  profile.outlineColor = $(Format-GlslVec3 $profile.outline.color);")
    $lines.Add('  return profile;')
    $lines.Add('}')
    $lines.Add('')
}

$lines.Add('DLCharacterProfile dlBuiltInCharacterProfile(int characterId)')
$lines.Add('{')
foreach ($profile in ($profiles | Sort-Object id)) {
    $constant = 'DL_CHARACTER_' + ([string] $profile.key).ToUpperInvariant()
    $functionSuffix = ([string] $profile.key).Substring(0, 1).ToUpperInvariant() + ([string] $profile.key).Substring(1)
    $lines.Add("  if (characterId == $constant)")
    $lines.Add('  {')
    $lines.Add("    return dlCharacterProfile$functionSuffix();")
    $lines.Add('  }')
}
$lines.Add('')
$lines.Add('  // Callers handle Custom separately. This is a deterministic fallback.')
if ($profiles.Count -gt 0) {
    $firstKey = [string] ($profiles | Sort-Object id | Select-Object -First 1).key
    $firstSuffix = $firstKey.Substring(0, 1).ToUpperInvariant() + $firstKey.Substring(1)
    $lines.Add("  return dlCharacterProfile$firstSuffix();")
}
else {
    throw 'At least one built-in character profile is required.'
}
$lines.Add('}')

$beginMarker = '// BEGIN GENERATED CHARACTER PROFILES'
$endMarker = '// END GENERATED CHARACTER PROFILES'
$generatedContent = ($lines -join "`n").TrimEnd()
$replacement = $beginMarker + "`n" + $generatedContent + "`n" + $endMarker
$pattern = '(?s)' + [Regex]::Escape($beginMarker) + '.*?' + [Regex]::Escape($endMarker)

$selectorBeginMarker = '// BEGIN GENERATED CHARACTER SELECTOR'
$selectorEndMarker = '// END GENERATED CHARACTER SELECTOR'
$selectorEntries = [System.Collections.Generic.List[object]]::new()
$selectorEntries.Add([pscustomobject]@{ Name = 'Custom'; Id = 0 })
foreach ($profile in ($profiles | Sort-Object id)) {
    $selectorEntries.Add([pscustomobject]@{
        Name = [string] $profile.displayName
        Id = [int] $profile.id
    })
}
$selectorLines = [System.Collections.Generic.List[string]]::new()
for ($index = 0; $index -lt $selectorEntries.Count; $index++) {
    $entry = $selectorEntries[$index]
    $escapedName = $entry.Name.Replace('\', '\\').Replace('"', '\"')
    $comma = if ($index -lt ($selectorEntries.Count - 1)) { ',' } else { '' }
    $selectorLines.Add("//:     `"$escapedName`": $($entry.Id)$comma")
}
$selectorReplacement = $selectorBeginMarker + "`n" + ($selectorLines -join "`n") + "`n" + $selectorEndMarker
$selectorPattern = '(?s)' + [Regex]::Escape($selectorBeginMarker) + '.*?' + [Regex]::Escape($selectorEndMarker)

foreach ($shaderPath in $ShaderPaths) {
    $source = [System.IO.File]::ReadAllText($shaderPath)
    if (-not [Regex]::IsMatch($source, $pattern)) {
        throw "Generated character profile markers are missing from $shaderPath."
    }

    if (-not [Regex]::IsMatch($source, $selectorPattern)) {
        throw "Generated character selector markers are missing from $shaderPath."
    }

    $updated = [Regex]::Replace($source, $pattern, $replacement, 1)
    $updated = [Regex]::Replace($updated, $selectorPattern, $selectorReplacement, 1)
    [System.IO.File]::WriteAllText($shaderPath, $updated, [System.Text.UTF8Encoding]::new($false))
    Write-Output "Updated generated character profiles in $shaderPath."
}

Write-Output "Generated $($profiles.Count) character profile(s)."
